Fix pch.cpp include for MSVC precompiled headers
The MSVC /Yc"pch.h" option expects the source file to use
#include "pch.h" (quotes, no directory prefix), not
#include <cryptopp/pch.h>.

This fixes error C2857: '#include' statement specified with the
/Ycpch.h command-line option was not found in the source file